version: '2'

services:
  mysql:
    container_name: mysql_container
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crashcourse
      MYSQL_USER: crashcourse
      MYSQL_PASSWORD: bTeohmeN6hSe
    volumes:
      - ./../volume_data:/var/lib/mysql
    ports:
      - "3306:3306"
# DOCKER COMMAND TO GET INSIDE MYSQL CONTAINER
# docker exec -it mysql_container mysql -uroot -proot
